from __future__ import annotations

import csv
import io
import json
import struct
from copy import deepcopy
from html import escape
from pathlib import Path
from typing import Any

from swatch_story.palette import contrast_ratio


def write_json_report(
    summary: dict[str, Any], output_path: str | Path, *, precision: int | None = None
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    report_summary = _summary_with_precision(summary, precision)
    path.write_text(
        json.dumps(report_summary, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


CSV_HEADER = [
    "rank",
    "hex",
    "r",
    "g",
    "b",
    "count",
    "percent",
    "luminance",
    "best_text_color",
    "label",
    "name",
]

SVG_FONT = (
    "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "
    "'Segoe UI', sans-serif"
)


def render_csv_report(summary: dict[str, Any], *, precision: int | None = None) -> str:
    output = io.StringIO(newline="")
    writer = csv.writer(output)
    writer.writerow(CSV_HEADER)
    for entry in summary["palette"]:
        red, green, blue = entry["rgb"]
        writer.writerow(
            [
                entry["rank"],
                entry["hex"],
                red,
                green,
                blue,
                entry["count"],
                _format_decimal(entry["percent"], precision),
                _format_decimal(entry["luminance"], precision),
                entry["best_text_color"],
                entry["label"],
                entry.get("name", ""),
            ]
        )
    return output.getvalue()


def write_csv_report(
    summary: dict[str, Any], output_path: str | Path, *, precision: int | None = None
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_csv_report(summary, precision=precision),
        encoding="utf-8",
        newline="",
    )


def render_ase_report(summary: dict[str, Any], *, title: str = "Swatch Story") -> bytes:
    blocks = [_ase_block(0xC001, _ase_string(title))]
    for entry in summary["palette"]:
        red, green, blue = (value / 255 for value in entry["rgb"])
        data = b"".join(
            [
                _ase_string(_ase_swatch_name(entry)),
                b"RGB ",
                struct.pack(">fffH", red, green, blue, 0),
            ]
        )
        blocks.append(_ase_block(0x0001, data))
    blocks.append(_ase_block(0xC002, b""))
    return b"".join(
        [
            b"ASEF",
            struct.pack(">HHI", 1, 0, len(blocks)),
            *blocks,
        ]
    )


def _ase_block(block_type: int, data: bytes) -> bytes:
    return struct.pack(">HI", block_type, len(data)) + data


def _ase_string(value: object) -> bytes:
    text = _single_line(value)
    encoded = f"{text}\0".encode("utf-16-be")
    return struct.pack(">H", len(encoded) // 2) + encoded


def _ase_swatch_name(entry: dict[str, Any]) -> str:
    label = str(entry["hex"])
    if "name" in entry:
        label = f"{label} {_single_line(entry['name'])}"
    return label


def _single_line(value: object) -> str:
    return " ".join(str(value).split())


def write_ase_report(
    summary: dict[str, Any], output_path: str | Path, *, title: str = "Swatch Story"
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(render_ase_report(summary, title=title))


def render_css_report(summary: dict[str, Any]) -> str:
    lines = ["/* Generated by swatch-story. */", ":root {"]
    for entry in summary["palette"]:
        rank = entry["rank"]
        rgb = ", ".join(str(value) for value in entry["rgb"])
        if "name" in entry:
            lines.append(f"  /* {escape_css_comment(str(entry['name']))} */")
        lines.extend(
            [
                f"  --swatch-story-color-{rank}: {entry['hex']};",
                f"  --swatch-story-color-{rank}-rgb: {rgb};",
                f"  --swatch-story-color-{rank}-text: {entry['best_text_color']};",
            ]
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def escape_css_comment(value: str) -> str:
    return value.replace("*/", "* /")


def write_css_report(summary: dict[str, Any], output_path: str | Path) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_css_report(summary), encoding="utf-8")


def render_gpl_report(summary: dict[str, Any], *, title: str = "Swatch Story") -> str:
    safe_title = " ".join(str(title).split())
    palette = summary["palette"]
    lines = [
        "GIMP Palette",
        f"Name: {safe_title}",
        f"Columns: {len(palette)}",
        "# Generated by swatch-story.",
    ]
    for entry in palette:
        red, green, blue = entry["rgb"]
        label = entry["hex"]
        if "name" in entry:
            label = f"{label} {entry['name']}"
        lines.append(f"{red:3d} {green:3d} {blue:3d} {label}")
    return "\n".join(lines) + "\n"


def write_gpl_report(
    summary: dict[str, Any], output_path: str | Path, *, title: str = "Swatch Story"
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_gpl_report(summary, title=title), encoding="utf-8")


def render_markdown_report(
    summary: dict[str, Any],
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> str:
    source = markdown_escape(str(summary["source"]))
    width = summary["size"]["width"]
    height = summary["size"]["height"]
    settings = summary.get("settings", {})
    cluster_distance = markdown_escape(str(settings.get("cluster_distance", 0)))
    palette = summary["palette"]
    include_names = any("name" in entry for entry in palette)
    header = "| Rank | Color | RGB | Percent | Luminance | Text | Label |"
    divider = "| ---: | --- | --- | ---: | ---: | --- | --- |"
    if include_names:
        header = "| Rank | Color | Name | RGB | Percent | Luminance | Text | Label |"
        divider = "| ---: | --- | --- | --- | ---: | ---: | --- | --- |"
    lines = [
        f"# {markdown_escape(title)}",
        "",
        f"Source: `{source}`  ",
        f"Size: {width} x {height} px  ",
        f"Colors: {len(palette)}  ",
        f"Cluster distance: {cluster_distance}",
        "",
        header,
        divider,
    ]
    for entry in palette:
        rgb = ", ".join(str(value) for value in entry["rgb"])
        row = [
            str(entry["rank"]),
            f"`{markdown_escape(entry['hex'])}`",
        ]
        if include_names:
            row.append(markdown_escape(str(entry.get("name", ""))))
        row.extend(
            [
                f"`{markdown_escape(rgb)}`",
                f"{_format_decimal(entry['percent'], precision)}%",
                _format_decimal(entry["luminance"], precision),
                markdown_escape(entry["best_text_color"]),
                markdown_escape(entry["label"]),
            ]
        )
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines) + "\n\n"


def markdown_escape(value: str) -> str:
    return (
        escape(value)
        .replace("|", "\\|")
        .replace("\r\n", "<br>")
        .replace("\r", "<br>")
        .replace("\n", "<br>")
    )


def write_markdown_report(
    summary: dict[str, Any],
    output_path: str | Path,
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_markdown_report(summary, title=title, precision=precision),
        encoding="utf-8",
    )


def render_text_report(
    summary: dict[str, Any],
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> str:
    settings = summary.get("settings", {})
    width = summary["size"]["width"]
    height = summary["size"]["height"]
    palette = summary["palette"]
    colors = _single_line(settings.get("colors", len(palette)))
    sample_step = _single_line(settings.get("sample_step", "unknown"))
    sample_limit = _single_line(settings.get("sample_limit", "unknown"))
    cluster_distance = _single_line(settings.get("cluster_distance", 0))
    sort = _single_line(settings.get("sort", "frequency"))
    ignored_color = _single_line(settings.get("ignore_color", "none"))
    names_enabled = bool(
        settings.get("color_names", any("name" in entry for entry in palette))
    )
    names_label = "included" if names_enabled else "not included"
    lines = [
        _single_line(title),
        "",
        f"Source: {_single_line(summary['source'])}",
        f"Image size: {width} x {height} px",
        (
            f"Settings: colors {colors}; sample step {sample_step}; "
            f"sample limit {sample_limit}; "
            f"cluster distance {cluster_distance}; sort {sort}; "
            f"ignored color {ignored_color}; names {names_label}"
        ),
        "",
        "Swatches:",
    ]
    for entry in palette:
        red, green, blue = entry["rgb"]
        line = (
            f"{entry['rank']}. {_single_line(entry['hex'])} | "
            f"rgb({red}, {green}, {blue}) | "
            f"{_format_decimal(entry['percent'], precision)}% | "
            f"{_single_line(entry['label'])} | "
            f"text {_single_line(entry['best_text_color'])}"
        )
        if "name" in entry:
            line = f"{line} | name {_single_line(entry['name'])}"
        lines.append(line)
    return "\n".join(lines) + "\n"


def write_text_report(
    summary: dict[str, Any],
    output_path: str | Path,
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_text_report(summary, title=title, precision=precision),
        encoding="utf-8",
    )


def render_svg_report(
    summary: dict[str, Any],
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> str:
    palette = summary["palette"]
    width = 960
    row_height = 128
    top_height = 190
    bottom_padding = 32
    height = top_height + (len(palette) * row_height) + bottom_padding
    safe_title = escape(str(title), quote=True)
    source = escape(str(summary["source"]), quote=True)
    image_width = escape(str(summary["size"]["width"]), quote=True)
    image_height = escape(str(summary["size"]["height"]), quote=True)
    settings = escape(_settings_summary(summary), quote=True)
    swatches = "\n".join(
        _render_svg_swatch(
            entry,
            y=top_height + (index * row_height),
            precision=precision,
        )
        for index, entry in enumerate(palette)
    )
    title_text = _svg_text(
        40,
        56,
        safe_title,
        fill="#222222",
        size=34,
        weight=700,
    )
    source_text = _svg_text(40, 94, f"Source: {source}", fill="#555555")
    size_text = _svg_text(
        40,
        124,
        f"Image: {image_width} x {image_height} px",
        fill="#555555",
    )
    settings_text = _svg_text(40, 154, settings, fill="#555555")
    svg_attrs = (
        f'xmlns="http://www.w3.org/2000/svg" width="{width}" '
        f'height="{height}" viewBox="0 0 {width} {height}" '
        'role="img" aria-labelledby="title desc"'
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg {svg_attrs}>
  <title id="title">{safe_title}</title>
  <desc id="desc">Palette swatch sheet for {source}</desc>
  <rect width="100%" height="100%" fill="#f7f7f5"/>
  {title_text}
  {source_text}
  {size_text}
  {settings_text}
{swatches}
</svg>
"""


def _settings_summary(summary: dict[str, Any]) -> str:
    settings = summary.get("settings", {})
    palette = summary["palette"]
    colors = _single_line(settings.get("colors", len(palette)))
    sample_step = _single_line(settings.get("sample_step", "unknown"))
    sample_limit = _single_line(settings.get("sample_limit", "unknown"))
    cluster_distance = _single_line(settings.get("cluster_distance", 0))
    sort = _single_line(settings.get("sort", "frequency"))
    ignored_color = _single_line(settings.get("ignore_color", "none"))
    names_enabled = bool(
        settings.get("color_names", any("name" in entry for entry in palette))
    )
    names_label = "included" if names_enabled else "not included"
    return (
        f"Settings: colors {colors}; sample step {sample_step}; "
        f"sample limit {sample_limit}; cluster distance {cluster_distance}; "
        f"sort {sort}; ignored color {ignored_color}; names {names_label}"
    )


def _render_svg_swatch(
    entry: dict[str, Any], *, y: int, precision: int | None = None
) -> str:
    hex_color = escape(str(entry["hex"]), quote=True)
    label = escape(_single_line(entry["label"]), quote=True)
    text_color = escape(_single_line(entry["best_text_color"]), quote=True)
    name = ""
    if "name" in entry:
        name = f" | Name {escape(_single_line(entry['name']), quote=True)}"
    details = escape(
        (
            f"{_format_decimal(entry['percent'], precision)}% | "
            f"Luminance {_format_decimal(entry['luminance'], precision)} | "
            f"Label {_single_line(entry['label'])} | "
            f"Text {_single_line(entry['best_text_color'])}"
        ),
        quote=True,
    )
    swatch_title = escape(f"{entry['rank']}. {entry['hex']}", quote=True)
    title_text = _svg_text(
        174,
        38,
        swatch_title,
        fill="#222222",
        size=23,
        weight=700,
    )
    details_text = _svg_text(174, 64, details, fill="#555555", size=16)
    label_text = _svg_text(174, 88, f"{label}{name}", fill="#555555", size=16)
    hex_text = _svg_text(
        42,
        59,
        hex_color,
        fill=text_color,
        size=18,
        weight=700,
    )
    return f"""  <g transform="translate(40 {y})">
    <rect x="0" y="0" width="880" height="104" rx="8" fill="#ffffff" stroke="#dddddd"/>
    <rect x="18" y="18" width="132" height="68" rx="6" fill="{hex_color}"/>
    {title_text}
    {details_text}
    {label_text}
    {hex_text}
  </g>"""


def _svg_text(
    x: int,
    y: int,
    text: str,
    *,
    fill: str,
    size: int = 17,
    weight: int | None = None,
) -> str:
    weight_attr = f' font-weight="{weight}"' if weight is not None else ""
    return (
        f'<text x="{x}" y="{y}" fill="{fill}" font-family="{SVG_FONT}" '
        f'font-size="{size}"{weight_attr}>{text}</text>'
    )


def write_svg_report(
    summary: dict[str, Any],
    output_path: str | Path,
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_svg_report(summary, title=title, precision=precision),
        encoding="utf-8",
    )


def render_html_report(
    summary: dict[str, Any],
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> str:
    safe_title = escape(title)
    source_name = escape(str(summary["source"]))
    source_path = escape(str(summary.get("source_path", summary["source"])))
    width = summary["size"]["width"]
    height = summary["size"]["height"]
    settings = summary.get("settings", {})
    colors = escape(str(settings.get("colors", len(summary["palette"]))))
    cluster_distance = escape(str(settings.get("cluster_distance", 0)))
    sample_step = settings.get("sample_step")
    sample_step_label = (
        f"Every {escape(str(sample_step))} pixel"
        if sample_step is not None
        else "Automatic"
    )
    names_enabled = bool(
        settings.get(
            "color_names",
            any("name" in entry for entry in summary["palette"]),
        )
    )
    swatches = "\n".join(
        render_swatch(entry, precision=precision) for entry in summary["palette"]
    )
    palette_count = len(summary["palette"])
    dominant = escape(str(summary["palette"][0]["hex"])) if palette_count else "none"
    swatch_label = "swatch" if palette_count == 1 else "swatches"
    names_label = "Included" if names_enabled else "Not included"
    sort_label = escape(str(settings.get("sort", "frequency")))
    ignore_color = settings.get("ignore_color")
    ignore_color_html = ""
    if ignore_color is not None:
        ignore_color_html = f"""      <div>
        <dt>Ignored color</dt>
        <dd>{escape(str(ignore_color))}</dd>
      </div>
"""
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{safe_title}</title>
  <style>
    :root {{
      color-scheme: light;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system,
        BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f7f7f5;
      color: #222222;
    }}
    body {{
      margin: 0;
      padding: 32px;
    }}
    main {{
      max-width: 960px;
      margin: 0 auto;
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 2.4rem;
      line-height: 1.05;
    }}
    .meta {{
      margin: 0 0 24px;
      color: #555555;
    }}
    .summary {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 12px;
      margin: 0 0 28px;
    }}
    .summary div {{
      border: 1px solid #dddddd;
      border-radius: 8px;
      background: #ffffff;
      padding: 14px;
    }}
    dt {{
      color: #666666;
      font-size: 0.78rem;
      font-weight: 700;
      margin: 0 0 4px;
      text-transform: uppercase;
    }}
    dd {{
      margin: 0;
      overflow-wrap: anywhere;
    }}
    .palette {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 14px;
    }}
    .swatch {{
      min-height: 290px;
      border: 1px solid rgba(0, 0, 0, 0.16);
      border-radius: 8px;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 16px;
      box-sizing: border-box;
    }}
    .rank {{
      font-size: 0.85rem;
      opacity: 0.72;
    }}
    .hex {{
      font-size: 1.35rem;
      font-weight: 700;
      overflow-wrap: anywhere;
    }}
    .details,
    .guidance {{
      font-size: 0.92rem;
      line-height: 1.45;
    }}
    .details dl,
    .guidance dl {{
      margin: 12px 0 0;
    }}
  </style>
</head>
<body>
  <main>
    <h1>{safe_title}</h1>
    <p class="meta">
      {palette_count} {swatch_label}; dominant color is {dominant}.
    </p>
    <dl class="summary" aria-label="Image and extraction summary">
      <div>
        <dt>Image name</dt>
        <dd>{source_name}</dd>
      </div>
      <div>
        <dt>Image path</dt>
        <dd>{source_path}</dd>
      </div>
      <div>
        <dt>Image size</dt>
        <dd>{width} x {height}px</dd>
      </div>
      <div>
        <dt>Requested colors</dt>
        <dd>{colors}</dd>
      </div>
      <div>
        <dt>Sample step</dt>
        <dd>{sample_step_label}</dd>
      </div>
      <div>
        <dt>Cluster distance</dt>
        <dd>{cluster_distance}</dd>
      </div>
      <div>
        <dt>Color names</dt>
        <dd>{names_label}</dd>
      </div>
      <div>
        <dt>Sort</dt>
        <dd>{sort_label}</dd>
      </div>
{ignore_color_html}\
    </dl>
    <section class="palette" aria-label="Extracted color palette">
{swatches}
    </section>
  </main>
</body>
</html>
"""


def render_swatch(entry: dict[str, Any], *, precision: int | None = None) -> str:
    hex_color = escape(entry["hex"])
    text_color = escape(entry["best_text_color"])
    label = escape(entry["label"])
    rgb = ", ".join(str(value) for value in entry["rgb"])
    style = escape(f"background: {entry['hex']}; color: {entry['best_text_color']}")
    contrast = contrast_ratio(
        tuple(entry["rgb"]),
        (0, 0, 0) if entry["best_text_color"] == "black" else (255, 255, 255),
    )
    contrast_text = escape(f"{contrast:.2f}:1")
    guidance = "WCAG AA for normal text" if contrast >= 4.5 else "Use for large text"
    name_line = ""
    if "name" in entry:
        name_line = f"""            <dt>Common name</dt>
            <dd>{escape(str(entry["name"]))}</dd>
"""
    return f"""      <article class="swatch" style="{style}">
        <div class="rank">#{entry["rank"]} - {label}</div>
        <div>
          <div class="hex">{hex_color}</div>
          <div class="details">
            <dl>
{name_line}\
              <dt>RGB</dt>
              <dd>{escape(rgb)}</dd>
              <dt>Share</dt>
              <dd>{_format_decimal(entry["percent"], precision)}% of sampled pixels</dd>
              <dt>Relative luminance</dt>
              <dd>{_format_decimal(entry["luminance"], precision)}</dd>
            </dl>
          </div>
          <div class="guidance">
            <dl>
              <dt>Best readable text</dt>
              <dd>Use {text_color} text</dd>
              <dt>Contrast ratio</dt>
              <dd>{contrast_text}; {guidance}</dd>
            </dl>
          </div>
        </div>
      </article>"""


def write_html_report(
    summary: dict[str, Any],
    output_path: str | Path,
    *,
    title: str = "Swatch Story",
    precision: int | None = None,
) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        render_html_report(summary, title=title, precision=precision),
        encoding="utf-8",
    )


def _format_decimal(value: object, precision: int | None) -> str:
    if precision is None:
        return str(value)
    return f"{float(value):.{precision}f}"


def _summary_with_precision(
    summary: dict[str, Any], precision: int | None
) -> dict[str, Any]:
    if precision is None:
        return summary
    report_summary = deepcopy(summary)
    for entry in report_summary["palette"]:
        entry["percent"] = round(float(entry["percent"]), precision)
        entry["luminance"] = round(float(entry["luminance"]), precision)
    return report_summary
