import json
from pathlib import Path

from swatch_story.report import (
    render_html_report,
    render_markdown_report,
    write_css_report,
    write_json_report,
    write_markdown_report,
)


def sample_summary() -> dict:
    return {
        "source": "sample.png",
        "size": {"width": 2, "height": 1},
        "palette": [
            {
                "rank": 1,
                "hex": "#112233",
                "rgb": [17, 34, 51],
                "count": 1,
                "percent": 50.0,
                "luminance": 0.015,
                "best_text_color": "white",
                "label": "dark",
            },
            {
                "rank": 2,
                "hex": "#eeeeee",
                "rgb": [238, 238, 238],
                "count": 1,
                "percent": 50.0,
                "luminance": 0.855,
                "best_text_color": "black",
                "label": "light",
            },
        ],
    }


def named_summary() -> dict:
    summary = sample_summary()
    summary["palette"][0]["name"] = "blue"
    summary["palette"][1]["name"] = "gray"
    return summary


def test_write_json_report_creates_readable_json(tmp_path: Path) -> None:
    output = tmp_path / "story.json"

    write_json_report(sample_summary(), output)

    data = json.loads(output.read_text(encoding="utf-8"))
    assert data["source"] == "sample.png"
    assert data["palette"][0]["hex"] == "#112233"


def test_html_report_escapes_title_and_contains_swatches() -> None:
    html = render_html_report(sample_summary(), title="<Palette & Story>")

    assert "&lt;Palette &amp; Story&gt;" in html
    assert "<Palette & Story>" not in html
    assert "#112233" in html
    assert "background: #112233" in html
    assert "color: white" in html


def test_html_report_includes_color_names_only_when_present() -> None:
    unnamed_html = render_html_report(sample_summary())
    named_html = render_html_report(named_summary())

    assert "Common name" not in unnamed_html
    assert "Common name blue" in named_html
    assert "Common name gray" in named_html


def test_write_css_report_creates_deterministic_custom_properties(
    tmp_path: Path,
) -> None:
    output = tmp_path / "nested" / "palette.css"

    write_css_report(sample_summary(), output)

    assert output.read_text(encoding="utf-8") == (
        "/* Generated by swatch-story. */\n"
        ":root {\n"
        "  --swatch-story-color-1: #112233;\n"
        "  --swatch-story-color-1-rgb: 17, 34, 51;\n"
        "  --swatch-story-color-1-text: white;\n"
        "  --swatch-story-color-2: #eeeeee;\n"
        "  --swatch-story-color-2-rgb: 238, 238, 238;\n"
        "  --swatch-story-color-2-text: black;\n"
        "}\n"
    )


def test_markdown_report_renders_portable_palette_table() -> None:
    markdown = render_markdown_report(sample_summary(), title="Palette <Story>")

    assert markdown == (
        "# Palette &lt;Story&gt;\n"
        "\n"
        "Source: `sample.png`  \n"
        "Size: 2 x 1 px  \n"
        "Colors: 2\n"
        "\n"
        "| Rank | Color | RGB | Percent | Luminance | Text | Label |\n"
        "| ---: | --- | --- | ---: | ---: | --- | --- |\n"
        "| 1 | `#112233` | `17, 34, 51` | 50.0% | 0.015 | white | dark |\n"
        "| 2 | `#eeeeee` | `238, 238, 238` | 50.0% | 0.855 | black | light |\n"
        "\n"
    )


def test_markdown_report_includes_color_names_only_when_present() -> None:
    unnamed_markdown = render_markdown_report(sample_summary())
    named_markdown = render_markdown_report(named_summary())

    assert "| Rank | Color | RGB | Percent | Luminance | Text | Label |" in (
        unnamed_markdown
    )
    assert "| Rank | Color | Name | RGB | Percent | Luminance | Text | Label |" in (
        named_markdown
    )
    assert "| 1 | `#112233` | blue | `17, 34, 51` |" in named_markdown


def test_write_markdown_report_creates_parent_directories(tmp_path: Path) -> None:
    output = tmp_path / "nested" / "story.md"

    write_markdown_report(sample_summary(), output, title="Palette Story")

    assert output.read_text(encoding="utf-8").startswith("# Palette Story\n")
